name: CI

on:
  push:
    paths-ignore:
      - '**.org'
  pull_request:
    paths-ignore:
      - '**.org'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.allow_failures}}

    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - snapshot

        allow_failures: [false]

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        eldev test

    - name: Run linter
      run: |
        eldev lint

    - name: Byte-compile project
      run: |
        eldev -dtT -C compile --set all --warnings-as-errors
